In [1]:
import pandas as pd
import requests
import json

from config import api_key

print(api_key)

c0TyOXk03aau8b4QMLV0uZh0hqgaGYCdKd9aPN61

In [21]:
base_url = "https://api.eia.gov/v2/electricity/retail-sales/data"

In [49]:
X_Params = {
    "api_key": api_key,
    "frequency": "monthly",
    "data[0]": "price",
    "facets": {},
    "start": "2021-01",
    "end": "2021-12",
    "sort[0][column]": "period",
    "sort[0][direction]": "desc",
    "offset": 0,
    "length": 5000
}

In [50]:
response = requests.get(base_url,params=X_Params).json()

In [51]:
sectorDF = pd.DataFrame(response["response"]["data"])
sectorDF.head()

,period,stateid,stateDescription,sectorid,sectorName,price,price-units
0,2021-12,ESC,East South Central,TRA,transportation,0.00,cents per kilowatthour
1,2021-12,IA,Iowa,ALL,all sectors,8.28,cents per kilowatthour
2,2021-12,IN,Indiana,TRA,transportation,10.67,cents per kilowatthour
3,2021-12,IN,Indiana,RES,residential,13.57,cents per kilowatthour
4,2021-12,IN,Indiana,OTH,other,NaN,cents per kilowatthour

In [52]:
sectorDF.dropna(subset=["price"],inplace=True,how="all")

In [53]:
sectorDF.head()

,period,stateid,stateDescription,sectorid,sectorName,price,price-units
0,2021-12,ESC,East South Central,TRA,transportation,0.00,cents per kilowatthour
1,2021-12,IA,Iowa,ALL,all sectors,8.28,cents per kilowatthour
2,2021-12,IN,Indiana,TRA,transportation,10.67,cents per kilowatthour
3,2021-12,IN,Indiana,RES,residential,13.57,cents per kilowatthour
5,2021-12,IN,Indiana,IND,industrial,7.69,cents per kilowatthour

In [55]:
sectorAgg = sectorDF.groupby("sectorid").agg(["mean","median","var","std","sem"])["price"]
sectorAgg

/var/folders/mr/rrsv97v15rv5fr542rb99_d80000gn/T/ipykernel_19896/1356841174.py:1: FutureWarning: ['period', 'stateid', 'stateDescription', 'sectorName', 'price-units'] did not aggregate successfully. If any error is raised this will raise in a future version of pandas. Drop these columns/ops to avoid this warning.
  sectorAgg = sectorDF.groupby("sectorid").agg(["mean","median","var","std","sem"])["price"]

               mean  median        var       std       sem
sectorid
ALL       11.895672  10.255  19.553045  4.421883  0.162114
COM       11.806290  10.575  17.447890  4.177067  0.153139
IND        8.432325   7.065  17.339783  4.164107  0.152664
RES       14.533871  12.815  22.342763  4.726813  0.173293
TRA        5.973118   7.115  27.595533  5.253145  0.192590

In [56]:
sectorTimeAgg = sectorDF.groupby(["sectorid","period"]).agg(["mean","median","var","std","sem"])["price"]
sectorTimeAgg

/var/folders/mr/rrsv97v15rv5fr542rb99_d80000gn/T/ipykernel_19896/1701385800.py:1: FutureWarning: ['stateid', 'stateDescription', 'sectorName', 'price-units'] did not aggregate successfully. If any error is raised this will raise in a future version of pandas. Drop these columns/ops to avoid this warning.
  sectorTimeAgg = sectorDF.groupby(["sectorid","period"]).agg(["mean","median","var","std","sem"])["price"]

                       mean  median        var       std       sem
sectorid period
ALL      2021-01  11.236774   9.585  18.408403  4.290501  0.544894
         2021-02  11.888710  10.315  18.791385  4.334903  0.550533
         2021-03  11.538548   9.920  19.399681  4.404507  0.559373
         2021-04  11.499194   9.800  18.766237  4.332002  0.550165
         2021-05  11.559194  10.085  18.301657  4.278044  0.543312
         2021-06  12.065484  10.495  18.350271  4.283722  0.544033
         2021-07  12.257903  10.700  19.443023  4.409424  0.559997
         2021-08  12.265645  10.705  18.936412  4.351599  0.552654
         2021-09  12.370323  10.605  21.012016  4.583887  0.582154
         2021-10  12.076774  10.315  20.849619  4.566138  0.579900
         2021-11  12.007581  10.375  20.674547  4.546927  0.577460
         2021-12  11.981935  10.205  23.799055  4.878428  0.619561
COM      2021-01  11.047097   9.775  15.744477  3.967931  0.503928
         2021-02  11.792742  10.460  16.489814  4.060765  0.515718
         2021-03  11.505161  10.135  16.508075  4.063013  0.516003
         2021-04  11.502903  10.295  16.327106  4.040681  0.513167
         2021-05  11.635484  10.470  16.391737  4.048671  0.514182
         2021-06  11.988065  10.730  17.097495  4.134912  0.525134
         2021-07  12.062258  10.735  18.444565  4.294714  0.545429
         2021-08  12.036452  10.715  17.872236  4.227557  0.536900
         2021-09  12.186129  10.735  19.047759  4.364374  0.554276
         2021-10  12.084355  10.745  18.791359  4.334900  0.550533
         2021-11  11.989516  10.865  17.987719  4.241193  0.538632
         2021-12  11.845323  10.540  20.602379  4.538984  0.576452
IND      2021-01   7.743871   6.330  16.107919  4.013467  0.509711
         2021-02   8.679677   7.585  16.748643  4.092511  0.519749
         2021-03   8.089194   6.895  17.136601  4.139638  0.525735
         2021-04   7.947258   6.420  15.733627  3.966564  0.503754
         2021-05   8.010484   6.655  15.747778  3.968347  0.503981
         2021-06   8.505000   7.195  16.661822  4.081890  0.518400
         2021-07   8.747419   7.445  16.902105  4.111217  0.522125
         2021-08   8.735161   7.380  16.855491  4.105544  0.521405
         2021-09   8.866613   7.415  18.332452  4.281641  0.543769
         2021-10   8.696290   7.110  18.960663  4.354384  0.553007
         2021-11   8.614355   7.170  18.712169  4.325756  0.549372
         2021-12   8.552581   7.010  21.710980  4.659504  0.591758
RES      2021-01  13.525000  11.710  21.474809  4.634092  0.588530
         2021-02  13.942258  12.200  22.820047  4.777033  0.606684
         2021-03  14.066613  12.320  22.859010  4.781110  0.607202
         2021-04  14.584355  12.675  22.378527  4.730595  0.600786
         2021-05  14.695484  13.065  21.043586  4.587329  0.582591
         2021-06  14.675323  13.070  20.416074  4.518415  0.573839
         2021-07  14.682097  13.015  21.660174  4.654049  0.591065
         2021-08  14.735161  13.055  21.180989  4.602281  0.584490
         2021-09  15.062581  13.140  23.597210  4.857696  0.616928
         2021-10  15.050484  13.385  22.519100  4.745429  0.602670
         2021-11  14.877097  13.180  23.325723  4.829671  0.613369
         2021-12  14.510000  12.595  26.466085  5.144520  0.653355
TRA      2021-01   5.694032   6.730  26.354838  5.133696  0.651980
         2021-02   5.800000   6.900  26.898698  5.186396  0.658673
         2021-03   5.742419   7.015  26.163219  5.114999  0.649606
         2021-04   5.930968   7.215  28.228163  5.313018  0.674754
         2021-05   5.942581   7.105  28.624537  5.350190  0.679475
         2021-06   6.040968   7.240  29.404560  5.422597  0.688671
         2021-07   6.053871   7.365  27.915955  5.283555  0.671012
         2021-08   6.129194   7.330  28.705280  5.357731  0.680432
         2021-09   6.235645   7.275  30.159192  5.491739  0.697451
         2021-10   5.945968   7.330  26.456716  5.143609  0.653239
         2021-11   6.099677   7.065  28.054341  5.296635  0.672673
         2021-12   6.062097   6.915  28.859469  5.372101  0.682258